# Generated by Django 4.2.26 on 2025-11-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrailleSpeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_count', models.IntegerField(verbose_name='패턴 수')),
                ('time_seconds', models.FloatField(verbose_name='시간 (초)')),
                ('speed_per_minute', models.FloatField(verbose_name='분당 속도')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='정확도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '점자 속도 로그',
                'verbose_name_plural': '점자 속도 로그',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=50, verbose_name='시험 유형')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='과목')),
                ('allocated_time', models.IntegerField(verbose_name='할당 시간 (분)')),
                ('used_time', models.IntegerField(verbose_name='사용 시간 (분)')),
                ('remaining_time', models.IntegerField(verbose_name='남은 시간 (분)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '시간 로그',
                'verbose_name_plural': '시간 로그',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WrongAnswerPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(blank=True, null=True, verbose_name='문제 ID')),
                ('wrong_answer', models.IntegerField(verbose_name='오답')),
                ('correct_answer', models.IntegerField(verbose_name='정답')),
                ('pattern_type', models.CharField(blank=True, max_length=50, verbose_name='패턴 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '오답 패턴',
                'verbose_name_plural': '오답 패턴',
                'ordering': ['-created_at'],
            },
        ),
    ]
