# Generated by Django 4.2.26 on 2025-11-26 01:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SisaWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='용어')),
                ('meaning', models.TextField(verbose_name='의미')),
                ('context', models.TextField(blank=True, verbose_name='맥락')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='출처')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '시사 용어',
                'verbose_name_plural': '시사 용어',
                'ordering': ['-date', 'word'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='단어')),
                ('meaning', models.TextField(verbose_name='의미')),
                ('example', models.TextField(blank=True, verbose_name='예문')),
                ('difficulty', models.IntegerField(choices=[(1, '쉬움'), (2, '보통'), (3, '어려움')], default=3, verbose_name='난이도')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '어휘',
                'verbose_name_plural': '어휘',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='VocabProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5, verbose_name='쉬움 인수')),
                ('interval', models.IntegerField(default=1, verbose_name='간격 (일)')),
                ('repetitions', models.IntegerField(default=0, verbose_name='반복 횟수')),
                ('next_due', models.DateTimeField(default=django.utils.timezone.now, verbose_name='다음 복습일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='vocab.vocabulary', verbose_name='어휘')),
            ],
            options={
                'verbose_name': '어휘 진행',
                'verbose_name_plural': '어휘 진행',
                'ordering': ['next_due'],
            },
        ),
        migrations.CreateModel(
            name='VocabQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='날짜')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_learned', models.BooleanField(default=False, verbose_name='학습 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='vocab.vocabulary', verbose_name='어휘')),
            ],
            options={
                'verbose_name': '어휘 큐',
                'verbose_name_plural': '어휘 큐',
                'ordering': ['date', 'order'],
                'unique_together': {('vocab', 'date')},
            },
        ),
    ]
