# Generated by Django 4.2.26 on 2025-11-26 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphTableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='graph_table/', verbose_name='이미지 파일')),
                ('patterns', models.JSONField(default=dict, verbose_name='추출된 패턴')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '그래프/도표',
                'verbose_name_plural': '그래프/도표',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='문제 내용')),
                ('choice1', models.CharField(blank=True, max_length=500, verbose_name='선택지 1')),
                ('choice2', models.CharField(blank=True, max_length=500, verbose_name='선택지 2')),
                ('choice3', models.CharField(blank=True, max_length=500, verbose_name='선택지 3')),
                ('choice4', models.CharField(blank=True, max_length=500, verbose_name='선택지 4')),
                ('choice5', models.CharField(blank=True, max_length=500, verbose_name='선택지 5')),
                ('correct_answer', models.IntegerField(verbose_name='정답 (1-5)')),
                ('explanation', models.TextField(blank=True, verbose_name='해설')),
                ('difficulty', models.IntegerField(choices=[(1, '쉬움'), (2, '보통'), (3, '어려움')], default=3, verbose_name='난이도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '문제',
                'verbose_name_plural': '문제',
                'ordering': ['unit', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='교재명')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='출판사')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='연도')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='과목')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '교재',
                'verbose_name_plural': '교재',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='단원명')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='exam.textbook', verbose_name='교재')),
            ],
            options={
                'verbose_name': '단원',
                'verbose_name_plural': '단원',
                'ordering': ['textbook', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.IntegerField(verbose_name='사용자 답안')),
                ('is_correct', models.BooleanField(verbose_name='정답 여부')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='응답 시간 (초)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.question', verbose_name='문제')),
            ],
            options={
                'verbose_name': '문제 시도',
                'verbose_name_plural': '문제 시도',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.unit', verbose_name='단원'),
        ),
    ]
