# Generated by Django 4.2.26 on 2025-11-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시간')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('total_questions', models.IntegerField(default=0, verbose_name='총 문제 수')),
                ('current_question_index', models.IntegerField(default=0, verbose_name='현재 문제 인덱스')),
                ('status', models.CharField(choices=[('running', '진행 중'), ('paused', '일시정지'), ('finished', '종료')], default='running', max_length=20, verbose_name='상태')),
                ('answers', models.JSONField(default=dict, verbose_name='답안')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '시험 세션',
                'verbose_name_plural': '시험 세션',
                'ordering': ['-started_at'],
            },
        ),
    ]
