# Generated by Django 4.2.26 on 2025-11-26 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrailleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cells', models.JSONField(default=list, verbose_name='점자 셀 배열')),
                ('strategy', models.CharField(choices=[('math', '수학'), ('korean', '국어'), ('english', '영어'), ('science', '과학'), ('social', '사회')], default='korean', max_length=20, verbose_name='과목별 전략')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('converting', '변환 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='변환 상태')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='변환 완료 시간')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='braille_contents', to='exam.unit', verbose_name='단원')),
            ],
            options={
                'verbose_name': '점자 변환 데이터',
                'verbose_name_plural': '점자 변환 데이터',
                'ordering': ['unit', '-created_at'],
                'indexes': [models.Index(fields=['unit', 'status'], name='exam_braill_unit_id_b8227c_idx'), models.Index(fields=['status'], name='exam_braill_status_4412cb_idx')],
            },
        ),
    ]
