# Generated by Django 4.2.26 on 2025-12-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_braillecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='지문 내용')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('sentences', models.JSONField(blank=True, default=list, verbose_name='문장 분리 결과')),
                ('paragraphs', models.JSONField(blank=True, default=list, verbose_name='단락 분리 결과')),
                ('central_sentences', models.JSONField(blank=True, default=list, verbose_name='중심 문장')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='키워드')),
                ('structure_analysis', models.JSONField(blank=True, default=dict, verbose_name='구조 분석 결과')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='exam.question', verbose_name='문제')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='exam.unit', verbose_name='단원')),
            ],
            options={
                'verbose_name': '지문',
                'verbose_name_plural': '지문',
                'ordering': ['unit', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_sentence_id', models.IntegerField(verbose_name='지문 문장 인덱스')),
                ('similarity_score', models.FloatField(verbose_name='의미 유사도 점수')),
                ('mapping_type', models.CharField(choices=[('direct', '직접 근거'), ('inference', '추론 근거'), ('contradiction', '모순 근거'), ('support', '지지 근거')], default='direct', max_length=20, verbose_name='매핑 타입')),
                ('context_sentences', models.JSONField(blank=True, default=list, verbose_name='주변 문장 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_mappings', to='exam.passage', verbose_name='지문')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_mappings', to='exam.question', verbose_name='문제')),
            ],
            options={
                'verbose_name': '근거 매핑',
                'verbose_name_plural': '근거 매핑',
                'ordering': ['question', '-similarity_score'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='선택지 번호 (1-5)')),
                ('text', models.TextField(verbose_name='선택지 내용')),
                ('evidence_sentences', models.JSONField(blank=True, default=list, verbose_name='근거 문장 ID')),
                ('logic_structure', models.JSONField(blank=True, default=dict, verbose_name='논리 구조')),
                ('wrong_answer_analysis', models.JSONField(blank=True, default=dict, verbose_name='오답 분석')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exam.question', verbose_name='문제')),
            ],
            options={
                'verbose_name': '선택지',
                'verbose_name_plural': '선택지',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BrailleChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(verbose_name='청크 인덱스')),
                ('cells', models.JSONField(default=list, verbose_name='3-cell 패킷')),
                ('semantic_type', models.CharField(choices=[('sentence', '문장'), ('word', '단어'), ('formula', '수식'), ('keyword', '키워드'), ('graph_pattern', '그래프 패턴'), ('choice', '선택지'), ('evidence', '근거')], default='sentence', max_length=50, verbose_name='의미 타입')),
                ('original_text', models.TextField(blank=True, verbose_name='원본 텍스트')),
                ('start_position', models.IntegerField(blank=True, null=True, verbose_name='원본 텍스트 시작 위치')),
                ('end_position', models.IntegerField(blank=True, null=True, verbose_name='원본 텍스트 끝 위치')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='braille_chunks', to='exam.choice', verbose_name='선택지')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='exam.braillecontent', verbose_name='점자 콘텐츠')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='braille_chunks', to='exam.passage', verbose_name='지문')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='braille_chunks', to='exam.question', verbose_name='문제')),
            ],
            options={
                'verbose_name': '점자 청크',
                'verbose_name_plural': '점자 청크',
                'ordering': ['content', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일 경로')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='파일 크기 (bytes)')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('uploading', '업로드 중'), ('parsing', '파싱 중'), ('analyzing', '분석 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('progress', models.IntegerField(default=0, verbose_name='진행률 (%)')),
                ('ocr_results', models.JSONField(blank=True, default=dict, verbose_name='OCR 결과')),
                ('layout_analysis', models.JSONField(blank=True, default=dict, verbose_name='레이아웃 분석 결과')),
                ('extracted_text', models.TextField(blank=True, verbose_name='추출된 텍스트')),
                ('image_areas', models.JSONField(blank=True, default=list, verbose_name='이미지 영역 정보')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('textbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to='exam.textbook', verbose_name='교재')),
            ],
            options={
                'verbose_name': 'PDF 문서',
                'verbose_name_plural': 'PDF 문서',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='exam_pdfdoc_status_be48d5_idx'), models.Index(fields=['textbook', 'status'], name='exam_pdfdoc_textboo_017a01_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='passage',
            index=models.Index(fields=['unit', 'order'], name='exam_passag_unit_id_ab54c8_idx'),
        ),
        migrations.AddIndex(
            model_name='passage',
            index=models.Index(fields=['question'], name='exam_passag_questio_09bcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencemapping',
            index=models.Index(fields=['question', 'similarity_score'], name='exam_eviden_questio_615b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencemapping',
            index=models.Index(fields=['passage', 'passage_sentence_id'], name='exam_eviden_passage_41362c_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question', 'order'], name='exam_choice_questio_e72bf9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'order')},
        ),
        migrations.AddIndex(
            model_name='braillechunk',
            index=models.Index(fields=['content', 'chunk_index'], name='exam_braill_content_f1898c_idx'),
        ),
        migrations.AddIndex(
            model_name='braillechunk',
            index=models.Index(fields=['semantic_type'], name='exam_braill_semanti_abada8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='braillechunk',
            unique_together={('content', 'chunk_index')},
        ),
    ]
